low_threshold: 0.15
high_threshold: 0.85
output_threshold: 0.5
features_fname: jsons/extracted_features_detr_500.json
full_csv: partial_labeled_sports.csv
prog_fname: prog_sports.txt
task: image
examples: null
num_examples: 15
heuristic: freq
num_feature_selection_rounds: 10
predicates_per_round: 10
use_bins: true
depth: 1
use_mutual_information: false
mutual_info_pool_size: 2
manual: true
eval: true
debug: false
