low_threshold: 0.2
high_threshold: 0.8
output_threshold: 0.5
features_fname: jsons/bach_features.json
full_csv: full_labeled_music.csv
prog_fname: prog_music.txt
task: music
examples: null
num_examples: 10
num_feature_selection_rounds: 5
predicates_per_round: 5
use_bins: true
depth: 4
use_mutual_information: true
mutual_info_pool_size: 2
manual: true
eval: true
debug: true
