low_threshold: 0.2
high_threshold: 0.8
output_threshold: 0.5
features_fname: extracted_features_gemini_500_5.json
full_csv: partial_labeled_sports.csv
prog_fname: prog_sports_gemini.txt
task: image
examples: null
num_examples: 10
num_feature_selection_rounds: 5
predicates_per_round: 5
use_bins: false
depth: 1
use_mutual_information: true
mutual_info_pool_size: 2
manual: false 
eval: true
debug: true
