low_threshold: 0.2
high_threshold: 0.8
json_filename: extracted_features.json
csv_filename: partial_labels.csv
num_feature_selection_rounds: 5
features_combine_count: 3
predicates_present_count: 5
use_mutual_information: true
manual: false
