low_threshold: 0.15
high_threshold: 0.85
output_threshold: 0.5
features_fname: jsons/bach_features.json
full_csv: labeled_music.csv
prog_fname: prog_music_hand_1.txt
task: music
examples: null
num_examples: 30
heuristic: freq
num_feature_selection_rounds: 10
predicates_per_round: 30
use_bins: true
depth: 1
use_mutual_information: false
mutual_info_pool_size: 2
manual: true
eval: true
debug: true
