low_threshold: 0.2
high_threshold: 0.8
features_fname: extracted_features_detr.json
examples_fname: partial_labeled_coco.csv
num_feature_selection_rounds: 5
features_combine_count: 3
predicates_per_round: 5
depth: 0
use_mutual_information: true
manual: false
